routes/web.php
Route::get('/admin/videos/create',   $controller_path . '\Admin\VideoController@create')->name('cms-videos.create');
Route::post('/admin/videos/store',   $controller_path . '\Admin\VideoController@store')->name('cms-videos.store');
Route::get('/admin/videos/edit/{id}',   $controller_path . '\Admin\VideoController@edit')->name('cms-videos.edit');
Route::post('/admin/videos/update/{id}',   $controller_path . '\Admin\VideoController@update')->name('cms-videos.update');
Route::get('/admin/videos/delete/{id}',   $controller_path . '\Admin\VideoController@delete')->name('cms-videos.delete');

Route::resource('/admin/skill',   $controller_path . '\Admin\SkillController')->except(['show']);
Route::get('/admin/skill/',   $controller_path . '\Admin\SkillController@index')->name('cms-skill.index');
Route::get('/admin/skill/create',   $controller_path . '\Admin\SkillController@create')->name('cms-skill.create');
Route::post('/admin/skill/store',   $controller_path . '\Admin\SkillController@store')->name('cms-skill.store');
Route::get('/admin/skill/edit/{id}',   $controller_path . '\Admin\SkillController@edit')->name('cms-skill.edit');
Route::post('/admin/skill/update/{id}',   $controller_path . '\Admin\SkillController@update')->name('cms-skill.update');
Route::get('/admin/skill/delete/{id}',   $controller_path . '\Admin\SkillController@delete')->name('cms-skill.delete');
// Route::get('/admin/skill/delete/{id}',   $controller_path . '\Admin\SkillController@delete')->name('skill.delete');

//region and country
// Route::resource('/admin/region',   $controller_path .'\Admin\RegionController')->except(['show']);
Route::get('/admin/region',  $controller_path .'\Admin\RegionController@index')->name('cms-region.index');
Route::get('/admin/region/create',   $controller_path .'\Admin\RegionController@create')->name('cms-region.create');
Route::post('/admin/region/store',   $controller_path .'\Admin\RegionController@store')->name('cms-region.store');
Route::get('/admin/region/edit/{id}',   $controller_path .'\Admin\RegionController@edit')->name('cms-region.edit');
Route::post('/admin/region/update/{id}',   $controller_path .'\Admin\RegionController@update')->name('cms-region.update');
Route::get('/admin/region/delete/{id}',   $controller_path .'\Admin\RegionController@delete')->name('cms-region.delete');
// Route::get('/admin/region/delete/{id}',   $controller_path .'\Admin\RegionController@delete')->name('region.delete');
//country
// Route::resource('/admin/country',   $controller_path .'\Admin\CountryController')->except(['show']);
Route::get('/admin/country',  $controller_path .'\Admin\CountryController@index')->name('cms-country.index');
Route::get('/admin/country/create',   $controller_path .'\Admin\CountryController@create')->name('cms-country.create');
Route::post('/admin/country/store',   $controller_path .'\Admin\CountryController@store')->name('cms-country.store');
Route::get('/admin/country/edit/{id}',   $controller_path .'\Admin\CountryController@edit')->name('cms-country.edit');
Route::post('/admin/country/update/{id}',   $controller_path .'\Admin\CountryController@update')->name('cms-country.update');
Route::get('/admin/country/delete/{id}',   $controller_path .'\Admin\CountryController@delete')->name('cms-country.delete');
//skill
Route::get('/admin/tutor/skills',  $controller_path .'\Admin\TutorController@getSkills')->name('skills');
//User
Route::resource('/admin/user', $controller_path .'\Admin\UserController');
Route::post('/admin/update/{id}', $controller_path .'\Admin\UserController@update')->name('user.update');
Route::get('/admin/delete', $controller_path .'\Admin\UserController@delete')->name('user.delete');
//admin tutor profile
Route::resource('/admin/tutor',  $controller_path .'\Admin\TutorController');
Route::post('/admin/tutor/store',  $controller_path .'\Admin\TutorController@store')->name('tutor.store');
Route::get('/admin/tutor/edit/{id}',  $controller_path .'\Admin\TutorController@edit')->name('admin.tutor.edit');
Route::post('/admin/tutor/update/{id}',  $controller_path .'\Admin\TutorController@update')->name('admin.tutor.update');
Route::get('/admin/tutor/delete/{id}',  $controller_path .'\Admin\TutorController@destroy')->name('admin.tutor.delete');


Route::get('/admin/tutor/portfolio/create/{id}/{showNext}', $controller_path .'\Admin\TutorController@createPortfolio')->name('tutor.portfolio.create');
Route::post('/admin/tutor/portfolio/{showNext}', $controller_path .'\Admin\TutorController@storePortfolio')->name('tutor.portfolio.store');
Route::get('/admin/tutor/portfolio/{id}/edit',  $controller_path .'\Admin\TutorController@editPortfolio')->name('tutor.portfolio.edit');
Route::post('/admin/tutor/portfolio/update/{id}',  $controller_path .'\Admin\TutorController@updatePortfolio')->name('tutor.portfolio.update');
Route::get('/admin/tutor/portfolio/delete/{id}', $controller_path .'\Admin\TutorController@deletePortfolio')->name('tutor.portfolio.delete');

// Route::get('/admin/tutor/package/{id}', $controller_path .'\Admin\TutorController@viewPackage')->name('tutor.package.view');
Route::get('/admin/tutor/package/view/{id}', $controller_path .'\Admin\TutorController@showPackage')->name('tutor.guru.show');
Route::get('/admin/tutor/package/create/{id}', $controller_path .'\Admin\TutorController@createPackage')->name('tutor.package.create');
Route::get('/admin/tutor/package/{id}/edit', $controller_path .'\Admin\TutorController@editPackage')->name('tutor.package.edit');
Route::post('/admin/tutor/package/store', $controller_path .'\Admin\TutorController@storePackage')->name('tutor.package.store');
Route::post('/admin/tutor/package/update/{id}', $controller_path .'\Admin\TutorController@updatePackage')->name('tutor.package.update');
Route::get('/admin/tutor/package/delete/{id}', $controller_path .'\Admin\TutorController@deletePackage')->name('tutor.package.delete');

Route::get('/admin/tutor/module/view/{empid}', [TutorController::class, 'showModule'])->name('tutor.module.show');
// Route::get('/admin/tutor/module/{id}',$controller_path .'\Admin\TutorController@viewModule')->name('tutor.module.view');
Route::get('/admin/tutor/module/create/{id}', $controller_path .'\Admin\TutorController@createModule')->name('tutor.module.create');
Route::get('/admin/tutor/module/{id}/edit', $controller_path .'\Admin\TutorController@editModule')->name('tutor.module.edit');
Route::post('/admin/tutor/module/store', $controller_path .'\Admin\TutorController@storeModule')->name('tutor.module.store');
Route::post('/admin/tutor/module/update/{id}', $controller_path .'\Admin\TutorController@updateModule')->name('tutor.module.update');
Route::get('/admin/tutor/module/delete/{id}',$controller_path .'\Admin\TutorController@deleteModule')->name('tutor.module.delete');

Route::get('/admin/tutor/liveclass/view/{id}', $controller_path .'\Admin\TutorController@showLiveClass')->name('tutor.live_class.show');
// Route::get('/admin/tutor/liveclass/{id}', 'Admin\TutorController@viewLiveClass')->name('tutor.live_class.view');
Route::get('/admin/tutor/liveclass/create/{id}', $controller_path .'\Admin\TutorController@createLiveClass')->name('tutor.live_class.create');
Route::post('/admin/tutor/liveclass/store', $controller_path .'\Admin\TutorController@storeLiveClass')->name('tutor.live_class.store');
Route::get('/admin/tutor/liveclass/edit/{id}', $controller_path .'\Admin\TutorController@editLiveClass')->name('tutor.live_class.edit');
Route::post('/admin/tutor/liveclass/update/{id}', $controller_path .'\Admin\TutorController@updateLiveClass')->name('tutor.live_class.update');
Route::get('/admin/tutor/liveclass/delete/{id}', $controller_path .'\Admin\TutorController@deleteBatch')->name('tutor.live_class.delete');
//commision
// Route::resource('/admin/generalsetting',  $controller_path .'\Admin\GeneralsettingController')->except(['show']);
Route::get('/admin/generalsetting/',  $controller_path .'\Admin\GeneralsettingController@index')->name('general-generalsetting.index');
Route::get('/admin/generalsetting/create',  $controller_path .'\Admin\GeneralsettingController@create')->name('general-generalsetting.create');
Route::post('/admin/generalsetting/store',   $controller_path .'\Admin\GeneralsettingController@store')->name('general-generalsetting.store');
Route::get('/admin/generalsetting/edit/{id}',  $controller_path .'\Admin\GeneralsettingController@edit')->name('general-generalsetting.edit');
Route::post('/admin/generalsetting/update/{id}',   $controller_path .'\Admin\GeneralsettingController@update')->name('general-generalsetting.update');
Route::get('/admin/generalsetting/delete/{id}',  $controller_path .'\Admin\GeneralsettingController@destroy')->name('general-generalsetting.delete');
//general settings
Route::get('/admin/generalsetting/view-currency', $controller_path .'\Admin\GeneralsettingController@viewCurrency')->name('general-admin.settings.viewCurrency');
Route::post('/admin/generalsetting/view-currency/store',  $controller_path .'\Admin\GeneralsettingController@currencyStore')->name('general-settings.currencyStore');
Route::post('/admin/generalsetting/view-currency/update', $controller_path .'\Admin\GeneralsettingController@currencyUpdate')->name('general-settings.currencyUpdate');

Route::get('/admin/generalsetting/view-currency/create',  $controller_path .'\Admin\GeneralsettingController@createCurrency')->name('general-admin.currency_settings.createCurrency');
Route::post('/admin/generalsetting/storeCurrency',   $controller_path .'\Admin\GeneralsettingController@storeCurrency')->name('general-admin.currency_settings.storeCurrency');
Route::get('/admin/generalsetting/view-currency/{id}/edit',  $controller_path .'\Admin\GeneralsettingController@editCurrency')->name('general-admin.currency_settings.editCurrency');
Route::post('/admin/generalsetting/updateCurrency/{id}',   $controller_path .'\Admin\GeneralsettingController@updateCurrency')->name('general-admin.currency_settings.updateCurrency');

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    public $table = "users";
     protected $fillable = [
        'name','commision','description','email','dob', 'slug','password','role','phone_number','location','token','otp_verification','profile_image','image_file_name'
    ];
    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function country()
    {
        return $this->belongsTo('\App\Models\Country', 'location', 'id');
    }
    public function TutorSkill()
    {
        return $this->hasOne('App\Models\TutorSkills', 'id','tutor_id');
    }
   
    public function tutorSkills() {
        return $this->hasMany(TutorSkills::class, 'tutor_id');
    }


}

resources/views/admin/user/create_edit.blade.php
@php
    $formAction = isset($user) ? route('user.update', $user->id) : route('user.store');
    $issetUser = isset($user) ? 1 : 0;
        $options=$countries;
    $grades=$grade;

@endphp
@extends('layouts/layoutMaster')
@section('vendor-style')
<link rel="stylesheet" href="{{asset('assets/vendor/libs/bs-stepper/bs-stepper.css')}}" />
<link rel="stylesheet" href="{{asset('assets/vendor/libs/bootstrap-select/bootstrap-select.css')}}" />
<link rel="stylesheet" href="{{asset('assets/vendor/libs/select2/select2.css')}}" />
<link rel="stylesheet" href="{{asset('assets/vendor/libs/formvalidation/dist/css/formValidation.min.css')}}" />
@endsection

@section('vendor-script')
<script src="{{asset('assets/vendor/libs/bs-stepper/bs-stepper.js')}}"></script>
<script src="{{asset('assets/vendor/libs/bootstrap-select/bootstrap-select.js')}}"></script>
<script src="{{asset('assets/vendor/libs/select2/select2.js')}}"></script>
<script src="{{asset('assets/vendor/libs/formvalidation/dist/js/FormValidation.min.js')}}"></script>
<script src="{{asset('assets/vendor/libs/formvalidation/dist/js/plugins/Bootstrap5.min.js')}}"></script>
<script src="{{asset('assets/vendor/libs/formvalidation/dist/js/plugins/AutoFocus.min.js')}}"></script>
@endsection



@section('page-script')
<script src="{{asset('assets/js/forms-selects.js')}}"></script>
<script src="{{asset('assets/js/user/form-validation.js')}}"></script>
@endsection
@section('content')

<div class="content">
  <div class="container-fluid">
    <div class="row d-flex justify-content-center">
      <div class="col-lg-12">
        <div class="card">
          <div class="card-header card-header-primary">
            <h4 class="card-title">
              @isset($user)
                  Edit Details
              @else
                  Add New User
              @endisset
            </h4>
            <p class="card-category">Complete your profile</p>
          </div>
          <div class="card-body">
            <form novalidate action="{{ $formAction }}" class="form" id="myForm" method="POST" accept-charset="UTF-8" enctype="multipart/form-data">
              @isset($user) @method('PUT') @endisset
              @csrf
              <div class="row g-3">
              <div class="col-sm-6">
                    <label class="form-label">Name</label>
                    <input id="name" type="text" name="name" class="form-control"
                        value="{{ old('name') ?? ($issetUser ? $user->name : '')  }}" {{($issetUser) ? '' : 'required'}}>
                        <div class="invalid-feedback">Name is required </div>
                  </div>
              
                  <div class="col-sm-6">
                          <label class="form-label">Dob</label>
                          <input id="dob" type="date" name="dob" class="form-control"
                                 value=" "{{($issetUser) ? '' : 'required'}}>
                                 <div class="invalid-feedback">DOB is required </div>
                      </div>
                
                      <div class="col-sm-6">
                    <label class="form-label">Email</label>
                    <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ old('email') ?? ($issetUser ? $user->email : '')  }}" {{($issetUser) ? '' : 'required'}} autocomplete="email">

                    <div class="invalid-feedback">Email is required </div>
                  </div>
               
                  <div class="col-sm-6">
                    <label class="form-label">Phone Number</label>
                    <input id="phone_number" type="number" class="form-control @error('phone_number') is-invalid @enderror" name="phone_number" value="{{ old('phone_number') ?? ($issetUser ? $user->phone_number : '')  }}" {{($issetUser) ? '' : 'required'}} autocomplete="phone_number">

                    <div class="invalid-feedback">Phone Number is required </div>
                  </div>
              
                  <div class="col-sm-6">
                    <label class="form-label">Password</label>
                    <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" {{($issetUser) ? '' : 'required'}} autocomplete="new-password">

                    <div class="invalid-feedback">Password is required </div>
                  </div>
               
                  <div class="col-sm-6">
                    <label class="form-label">Confirm Password</label>
                    <input id="password-confirm" type="password" class="form-control" name="password_confirmation" {{($issetUser) ? '' : 'required'}} autocomplete="new-password">
                    <div class="invalid-feedback">Confirm Password is required </div>
                  </div>
                

              <!-- <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label class="bmd-label-floating">Parent Name</label>
                    <input id="parent_name" type="text" name="parent_name" class="form-control"
                           value="{{ old('parent_name') ?? ($issetUser ? $user->student_detail->parent_name : '')  }}">
                    @error ('parent_name')
                    <p class="text-danger">{{ $message }}</p>
                    @enderror
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label class="bmd-label-floating">Parent Email</label>
                    <input id="parent_email" type="text" name="parent_email" class="form-control"
                           value="{{ old('parent_email') ?? ($issetUser ? $user->student_detail->parent_email : '')  }}">
                    @error ('parent_email')
                    <p class="text-danger">{{ $message }}</p>
                    @enderror
                  </div>
                </div>
              </div> -->

              <!-- <div class="row"> -->
                <!-- <div class="col-md-6">
                  <div class="form-group">
                    <label class="bmd-label-floating">Parent Mobile</label>
                    <input id="parent_mobile" type="text" name="parent_mobile" class="form-control"
                           value="{{ old('parent_mobile') ?? ($issetUser ? $user->student_detail->parent_mobile : '')  }}">
                    @error ('parent_mobile')
                    <p class="text-danger">{{ $message }}</p>
                    @enderror
                  </div>
                </div> -->
                 
                <div class="col-sm-6">
                <label class="form-label" for="category[]">Category<span class="text-danger">*</span></label>
                <select name="category[]" id="category" class="select2 form-select" multiple data-dropdown-css-class="select2-purple" data-placeholder="Select Category" required>
                
                        @foreach ($categories as $categorie)

                        <option  value="{{ $categorie->id }}"> {{ $categorie->category_name }}</option>
                        @endforeach
                    
                  </select>
                  <div class="invalid-feedback">Category is required </div>
              </div>
              <div class="col-sm-6">
                <label class="form-label" for="skills[]">Skill<span class="text-danger">*</span></label>
                <select name="skills[]" id="skills" class="select2 form-select" multiple data-dropdown-css-class="select2-purple" data-placeholder="Select one or more Skills" required>
                
                        <!-- @foreach ($skill_subset as $skill)
        
                       
                        <option  value="{{ $skill->id }}"> {{ $skill->skill_name }}</option>
                        @endforeach -->
                    
                  </select>
                  <div class="invalid-feedback">Skill is required </div>
              </div>
              <div class="col-sm-6">
                <label class="form-label" for="location">Country<span class="text-danger">*</span></label>
                <select   data-placeholder="Select a country"  name="location" id="location" class="select2 form-select form-select" data-allow-clear="true">
                                      
                        @foreach ($options as $key => $value)
                        <option value="{{ $value['id'] }}"  {{ $value['country_name'] == 'India' ? 'selected' : '' }}>{{ $value['country_name'] }}</option>
                      @endforeach
</select>
</div>
                  
              
                      <div class="col-sm-6">
                          <label class="form-label">Grade</label>
                          <select name="grade" id="grade" class="select2 form-select  @error('grade') is-invalid @enderror" required>
                              <option value=""></option>
                              @foreach ($grades as $key => $value)
                                  <option value="{{ $value['id'] }}" {{($issetUser && $user->student_detail->grade == $value['id']) ? 'selected' : ''}}>{{ $value['grade_name'] }}</option>
                              @endforeach
                          </select>
                          <div class="invalid-feedback">Grade is required </div>
                      </div>
                      <div class="col-sm-6">
                <label class="form-label" for="profile_image">Profile Picture<span class="text-danger">*</span></label>
                <input type="file" name="profile_image" id="profile_image" class="form-control" />
                <div id="valid_profile" style="font-size: 13px;display: block;"><b>.PNG .JPG </b></div>
              </div>
              <div class="col-sm-6">
                <label class="form-label" for="description">Description<span class="text-danger">*</span></label>
                <textarea name="description" id="description" class="form-control"  ></textarea>
              </div>

                      <div class="row g-3">
<div class="col-12 d-flex justify-content-between">
              <a href="{{ route('user.index') }}"  class= "pull-right">
                        <button type="button"  class="btn btn-primary  btn-sm">
                          Back
                        </button>
                      </a>
                     <button type="submit" id ="submit" name="submit_button" class="btn btn-primary btn-sm pull-right" >Submit</button>
         </div>
         </div>
         </div>  
            </form>
          </div>
        </div>
      </div>
    </div>
    <!-- @isset($user)
    <div class="row d-flex justify-content-center">
      <div class="col-lg-8">
        <div class="card">
          <div class="card-header card-header-primary">
            <h4 class="card-title">
              Delete this User
            </h4>
          </div>
          <div class="card-body">
            <form action="{{ route('user.destroy', $user->id) }}" method="POST">
                @csrf
                @method('DELETE')
              <div class="row">
                <div class="col-md-12">
                  Do you really want to do this ? Make sure you are selected the right item. This action is irreversible.
                  All data associated with this item will be erased permanantly.
                </div>
              </div>
              <button type="submit" class="btn btn-primary pull-right">Delete</button>
              <div class="clearfix"></div>
            </form>
          </div>
        </div>
      </div>
    </div>
    @endisset -->
  </div>
</div>
@endsection
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.js"></script>
  <script type="text/javascript">
    
 $( document ).ready(function() {
  
  $('#category').change(function () {
    
        var category_ids = $(this).val();

        $.ajax({
            url: '{{ route('skills') }}',
            type: 'GET',
            data: {
                'category_ids': category_ids
            },
            success: function (response) {
              console.log(response);
                var options = '<option value="">Select one or more skills</option>';

                $.each(response, function (key, skill) {
                    options += '<option value="' + skill.id + '">' + skill.skill_name + '</option>';
                });

                $('#skills').html(options);
            }
        });
    });

  });
    </script>

resources/views/admin/user/index.blade.php
@extends('layouts/layoutMaster')

@section('title', 'Student List ')

@section('content')

<div class="card">
<div class="card-header card-header-info">
<div class="dt-buttons btn-group flex-wrap">
     <div class="btn-group">
     </div>
     <a  href="{{route('user.create')}}">
       <button class="btn btn-secondary add-new btn-primary" tabindex="0"
        aria-controls="DataTables_Table_0" type="button">
        <span><i class="ti ti-plus me-0 me-sm-1 ti-xs"></i>
        <span class="d-none d-sm-inline-block">Add </span>
      </span></button></a>
     </div>
</div>
  <div class="card-datatable table-responsive">
 
    <table id="example" class="datatables-users table border-top">
                <thead>
                  <th>ID</th>
                  <th>Name</th>
                  <th>Email</th>
                  <th>Phone</th>
                  <th class="text-center">Action</th>
                </thead>
                <tbody>
                  @isset($users)
                  @foreach($users as $user)
                  <tr>
                    <td>{{$loop->index + 1}}</td>
                    <td>{{$user->name}}</td>
                    <td>{{$user->email}}</td>
                    <td>{{$user->phone_number}}</td>
                    <td>
                    <div class="d-flex align-items-center">
            <div class="dropdown">
              <button type="button" class="btn p-0 dropdown-toggle hide-arrow" data-bs-toggle="dropdown"><i class="ti ti-dots-vertical"></i></button>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="{{ route('user.edit', $user->id) }}"><i class="ti ti-pencil me-1"></i> Edit</a>
                <a class="dropdown-item" href="{{ route('user.delete', $user->id) }}"><i class="ti ti-trash me-1"></i> Delete</a>
              </div>
            </div>
<a href="{{ route('user.show', $user->id) }}" class="text-body"><i class="ti ti-eye ti-sm me-2"></i></a>
</div>
                    </td>
                  </tr>
                  @endforeach
                  @endisset
                </tbody>
              </table>
            </div>
          </div>
        
@endsection